### ISSUE TITLE
Agregar Contenido a la Página de Inicio

### ISSUE THREAD

**Issue by fvillena** [fvillena/faq#2]
¿Qué contenido podría ser?

**Comment by dquenti** [comment]
el hospital tiene su twiter y facebook actualizados con noticias(obvio esas páginas no las pueden ver, pero al redireccionar esas notician con el vínculo que traen redirigen a las noticias de la página del hospital como por ejemplo esta: https://www.redclinica.cl/hospital-clinico/noticias-c/newsid/1288.aspx?platform=hootsuite (pero desde la misma página del hospital, nosé como ver las noticias anteriores). Podría ser eso o no? 
¿lo otro sería como decían ustedes que por ejemplo aparezca cada día un procedimiento distnto en la página?

**Comment by fvillena** [comment]
Intentaré mostrar las últimas publicaciones de twitter en el inicio junto con una entrada al azar.

**Comment by fvillena** [comment]
Agregué una entrada al azar y las últimas publicaciones de twitter.
