### ISSUE TITLE
Agregar Contenido a la Página de Buscador

### ISSUE THREAD

**Issue by fvillena** [fvillena/faq#3]
¿La tabla completa u otro contenido?

**Comment by dquenti** [comment]
¿Tienen alguna forma de ver la taba completa? por ejemplo, si quisieran simplemente vitrinear por los procedimientos, para ver qué exámenes existen, cuales no conocen o simplemente si quieren aprender acerca de cualquier examen que no conozcan(como no lo conocerán no podrán buscarlo).
Si esto no es posible, creo que podría ir la tabla completa acá. Eso sí igual puede quedar sujeto a modificaciones el día martes

**Comment by fvillena** [comment]
Me parece una buena idea, porque efectivamente hasta el momento no hay una forma intuitiva de acceder a la lista completa, (sólo al ingresar una búsqueda vacía se accede a la lista completa.

**Comment by fvillena** [comment]
Ahora cuando se ingresa a la pestaña de búsqueda, por defecto aparecen todas las entradas
